-- Reset migration - drop all existing objects
DROP TABLE IF EXISTS credit_transactions CASCADE;
DROP TABLE IF EXISTS generation_logs CASCADE;
DROP TABLE IF EXISTS canva_orders CASCADE;
DROP TABLE IF EXISTS generated_ads CASCADE;
DROP TABLE IF EXISTS ad_folders CASCADE;
DROP TABLE IF EXISTS ad_concepts CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS subscription_tiers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS prompt_templates CASCADE;
DROP TABLE IF EXISTS system_config CASCADE;

DROP TYPE IF EXISTS member_type CASCADE;
DROP TYPE IF EXISTS member_status CASCADE;
DROP TYPE IF EXISTS member_auth_type CASCADE;
DROP TYPE IF EXISTS subscription_tier CASCADE;
DROP TYPE IF EXISTS subscription_status CASCADE;
DROP TYPE IF EXISTS billing_interval CASCADE;
DROP TYPE IF EXISTS brand_industry CASCADE;
DROP TYPE IF EXISTS brand_voice CASCADE;
DROP TYPE IF EXISTS concept_category CASCADE;
DROP TYPE IF EXISTS aspect_ratio CASCADE;
DROP TYPE IF EXISTS generation_status CASCADE;
DROP TYPE IF EXISTS canva_order_status CASCADE;
DROP TYPE IF EXISTS admin_role CASCADE;
DROP TYPE IF EXISTS prompt_template_type CASCADE;
DROP TYPE IF EXISTS api_type CASCADE;
DROP TYPE IF EXISTS ad_status CASCADE;
DROP TYPE IF EXISTS payment_status CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;
